extends: 
  - airbnb-base
  - eslint:recommended
  - plugin:react/recommended
globals:
  document: true
  window: true
rules:
  no-console: 0
  comma-dangle:
    - 2
    - always-multiline
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  react/jsx-filename-extension: 0
  react/jsx-indent:
    - error
    - 2
  react/react-in-jsx-scope: off
  react/prop-types: 0
  linebreak-style: 0
  semi:
    - 2
    - always
plugins:
  - react
